### ISSUE TITLE
getTemperature_c broken

### ISSUE THREAD

**Issue by lpdunwell** [pozyxLabs/Pozyx-Arduino-library#33]
locally, i get a static 34C, remote always 0C

**Comment by samuelvdv** [comment]
Hello,

There is no dedicated temperature sensor on the pozyx board, it uses the temperature provided by the motion sensor. The 34 C seems correct for the temperature on the motion sensor (accelerometer). 
Because the motion sensor is not available on the anchors, it is not possible to read the temperature from anchors.
I will make this more clear in the documentation.
