### ISSUE TITLE
ranging each other simultaneously 

### ISSUE THREAD

**Issue by supersc** [pozyxLabs/Pozyx-Arduino-library#56]
HI: 
when I have two devices (regardless of tag/anchor) and running doRange sketch to range each other simultaneously, I often get error back. Same goes with doDiscovery sketch.

Is this recognized? what is the reason behind it?

Thanks

**Comment by samuelvdv** [comment]
Hello,
when multiple devices are trying to use ultra-wideband at the same time, the signals will interfere resulting in an errors. This is similar to two people trying to speak at the same time. 
Because CSMA is not possible with UWB (carrier sense multiple access), the only way to solve this is to allocate slots to each device: you can have a 'master' tag that dictates other tags to perform ranging one-after-the-other. The DoRemoteRanging and DoRemotePositioning are functions specifically for this purpose.

Hope this helps,
